agents:
  competitor_scraper:
    role: "Competitor Price Intelligence Specialist"
    goal: "Extract comprehensive pricing data from competitor websites for electronic devices with high accuracy and efficiency"
    backstory: |
      You are an expert web scraping specialist with deep knowledge of e-commerce platforms.
      Your mission is to gather accurate pricing information from multiple sources while
      respecting website policies and rate limits. You excel at handling dynamic content,
      dealing with anti-scraping measures, and extracting structured data from unstructured sources.
    max_execution_time: 300
    max_iter: 5
    verbose: true
    allow_delegation: false
    
  price_optimizer:
    role: "Strategic Pricing Analyst"
    goal: "Develop optimal pricing strategies that maximize profit while maintaining competitive positioning"
    backstory: |
      You are a seasoned pricing strategist with expertise in competitive analysis and market dynamics.
      Your specialty lies in analyzing competitor pricing patterns, understanding market positioning,
      and developing data-driven pricing strategies that balance profitability with market competitiveness.
      You consider factors like brand positioning, customer psychology, and market trends.
    max_execution_time: 180
    max_iter: 3
    verbose: true
    allow_delegation: false
    
  impact_simulator:
    role: "Business Impact Analyst"
    goal: "Provide comprehensive impact analysis and predictions for pricing strategy decisions"
    backstory: |
      You are a business analyst specializing in predictive modeling and impact assessment.
      Your expertise includes forecasting sales volumes, revenue projections, market share analysis,
      and competitive response modeling. You excel at translating pricing strategies into
      business outcomes and providing actionable insights for decision-makers.
    max_execution_time: 240
    max_iter: 4
    verbose: true
    allow_delegation: false

tasks:
  scraping:
    description_template: |
      Scrape pricing data for the product: {product_name} with specifications: {specifications}
      
      Your task involves:
      1. Search for the exact product across {max_websites} major e-commerce platforms
      2. Extract pricing information, availability, ratings, and key features
      3. Handle disambiguation if product specifications are unclear
      4. Store structured data in vector database for analysis
      5. Validate data quality and completeness
      
      Focus on electronic devices only. If the product is not an electronic device, 
      politely decline and ask for a valid electronic product.
    
  optimization:
    description_template: |
      Analyze competitor pricing data and develop optimal pricing strategy for: {product_name}
      
      Your analysis should include:
      1. Competitive positioning analysis
      2. Price elasticity considerations
      3. Profit margin optimization
      4. Market penetration vs. premium positioning strategies
      5. Seasonal and trend-based adjustments
      6. Risk assessment for different pricing approaches
      
      Provide clear, actionable pricing recommendations with supporting rationale.
    
  simulation:
    description_template: |
      Conduct comprehensive impact simulation for the proposed pricing strategy of: {product_name}
      
      Your simulation should cover:
      1. Revenue projections under different scenarios
      2. Market share impact analysis
      3. Competitive response predictions
      4. Customer acquisition vs. retention trade-offs
      5. Sensitivity analysis for key assumptions
      6. Implementation timeline and milestones
      
      Present findings in clear, executive-ready format with visualizations.

llm_config:
  model: "gemini-2.0-flash-exp"
  temperature: 0.1
  max_tokens: 4096
  
tools_config:
  web_scraper:
    timeout: 30
    max_retries: 3
    delay_between_requests: 2
    
  vector_db:
    index_name: "pricing-data"
    dimension: 768
    metric: "cosine"
    
  price_analysis:
    profit_margin_min: 0.05
    profit_margin_max: 0.30
    competitive_threshold: 0.15